import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:printing/printing.dart';

import '../../data/models/scan_model.dart';

class PdfService {
  Future<void> generateAndSavePdf(ScanModel scan) async {
    final pdf = pw.Document();

    pdf.addPage(
      pw.MultiPage(
        pageFormat: PdfPageFormat.a4,
        margin: const pw.EdgeInsets.all(32),
        build: (pw.Context context) {
          return [
            pw.Text(
              scan.title,
              style: pw.TextStyle(fontSize: 22, fontWeight: pw.FontWeight.bold),
            ),
            pw.SizedBox(height: 4),
            pw.Text(
              "Generated by SwiftScan • ${scan.dateTime.day}/${scan.dateTime.month}/${scan.dateTime.year}",
              style: const pw.TextStyle(fontSize: 10, color: PdfColors.grey),
            ),
            pw.Divider(height: 20, thickness: 0.5),

            // Raw Text Body
            pw.Paragraph(
              text: scan.rawText,
              style: const pw.TextStyle(fontSize: 12, lineSpacing: 2),
            ),
          ];
        },
      ),
    );

    // Opens the native print/share preview
    await Printing.sharePdf(
      bytes: await pdf.save(),
      filename: 'SwiftScan_${scan.title.replaceAll(' ', '_')}.pdf',
    );
  }
}
